spring:
    datasource:
        url: jdbc:mysql://localhost:3306/blogs4u
        username: bestuser
        password: bestuser
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

security:

    jwt:
        secret: 48a868a4042f634ac04a117f00a87202131dd7c46c4b32c4acb3edc5e15f4511
        lifetime: 3600000 # 60 min
#        lifetime: 180000 # 3 min

    refresh_token:
        lifetime: 36000000 # 600 min
#        lifetime: 360000 # 6 min

server:
    error:
        include-message: always